/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentation;

import Process.*;
import Data.Connect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author K-P-P-K
 */
public class TimNhanVien extends javax.swing.JFrame {
Connection conn=null;
    /**
     * Creates new form TimNhanVien
     */
    public TimNhanVien() {
        initComponents();
        Show_BangNV_In_JTable();
    }
    public ArrayList<BangNV> BangNVList(String Tim)
    {   
         String User; 
         String Pass ; 
         String HoTenNV;
         int NamSinh;
         int Gioitinh;
         int TimGT=2;
        if (Tim.equals("Nam")==true)TimGT=1; 
        if (Tim.equals("Nữ")==true) TimGT=0; 
         String ChucVu;
        ArrayList<BangNV> BangNVList=new ArrayList<BangNV>();
        Connect con = new Connect();
        conn=con.ConnectDB();
        String query="SELECT * from nhanvien INNER JOIN chucvu on nhanvien.macv=chucvu.macv WHERE idnv Like '%"+Tim+"%' or honv Like '%"+Tim+"%' or tennv Like '%"+Tim+"%' or namsinh Like '%"+Tim+"%' or chucvu.macv Like '%"+Tim+"%' or gioitinh Like '%"+TimGT+"%' or tencv Like '%"+Tim+"%'  or phucapvc Like '%"+Tim+"%'";
        Statement st;
        ResultSet rs;
        BangNV Bang;
        try{
            st=conn.createStatement();
            rs=st.executeQuery(query);
            while(rs.next())
            {
               User=rs.getString("idnv");
               Pass=rs.getString("pass");
               HoTenNV=rs.getString("honv")+" "+rs.getString("tennv");
               NamSinh=rs.getInt("namsinh");
               Gioitinh=rs.getInt("gioitinh");
               ChucVu=rs.getString("tencv");
               Bang = new BangNV(User,Pass,HoTenNV,NamSinh,Gioitinh,ChucVu);
               BangNVList.add(Bang);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        return BangNVList;
    }
    
    public void Show_BangNV_In_JTable()
    {
      ArrayList<BangNV> list=BangNVList(txtTim.getText());
       DefaultTableModel model = new DefaultTableModel();
      model.setColumnIdentifiers(new Object[]{"User","Pass","HoTen","NamSinh","Gioitinh","ChucVu"});
      Object[] row=new Object[6];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getUser();
            row[1]=list.get(i).getPass();
            row[2]=list.get(i).getHoTen();
            row[3]=list.get(i).getNamSinh();
            row[4]=list.get(i).getGioitinh();
            row[5]=list.get(i).getChucVu();
        model.addRow(row);
        }
     BangTim.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtTim = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangTim = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Tìm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BangTim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "User", "Pass", "HoTen", "NamSinh", "GioiTinh", "ChucVu"
            }
        ));
        jScrollPane1.setViewportView(BangTim);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Show_BangNV_In_JTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TimNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TimNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TimNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TimNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangTim;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtTim;
    // End of variables declaration//GEN-END:variables
}
